import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import Nav from './Nav.js';
import homeimg from "../public/homeimg.jpg";
import Link from 'next/link';
export default function Home() {
  
  return (
    <div className={styles.container}>
    
    <Head>

      <title>Techoverflow</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      
    </Head>
    
    <main className={styles.main}>
    
      <h1 className={styles.title}>
       <span className="myspan"> BlogSite</span>
      </h1>

      <p className={styles.description}>
      Hello Welcome to New BlogSite
       
      </p>
      <div className={styles.blog}>
        <div className={styles.create}>
        <Link href="/createblog">
        <button>Create Blog</button>
        </Link>
           
        </div>
        <div className={styles.read}>
        <Link href="#showblog">
        <button>Show Blog</button>
        </Link>
        
        </div>
      </div>
     
      <Image className={styles.image} src={homeimg} alt="" width={2000} height={800}
      />
      {/* <img className={styles.image} src="/public/homeimg.jpg" alt="" width={2000} height={800} aly=""
      /> */}
      <section id='showblog'>
      <div className={styles.grid}>
        <a href="https://techbootcamps.utexas.edu/blog/best-ways-to-learn-javascript/" className={styles.card}>
          <h2>How to learn JavaScript in 2022 &rarr;</h2>
          <p>JavaScript is the language to create a logic and design a the web.</p>
        </a>

        <a href="https://radixweb.com/blog/nextjs-vs-react" className={styles.card}>
          <h2>React vs React with Next.js &rarr;</h2>
          <p>Advantages of using next.js istead of react</p>
        </a>

        <a
          href="https://kenzie.snhu.edu/blog/front-end-vs-back-end-whats-the-difference/#:~:text=Front%20and%20back%20end%20developers,see%20(the%20server%20side)."
          className={styles.card}
        >
          <h2>Frontend vs backend &rarr;</h2>
          <p>How Frontend and Backend contribute in a website to run a effective functionality website.</p>
        </a>

        <a
          href="https://blog.back4app.com/front-end-and-back-end-frameworks/"
          className={styles.card}
        >
          <h2>All frameworks of Frontend and Backend  &rarr;</h2>
          <p>
            Here all types of Frontend and Backend framework is describe shortly.
          </p>
        </a>
      </div>
      </section>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          soumyadip❤️
        </span>
      </a>
    </footer>
  </div>
  )
}
