import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import Nav from './Nav.js';
import homeimg from "../public/homeimg.jpg";
import Link from 'next/link';
import createblog from "./models/createblog"
import mongoose from 'mongoose';
export default function Home({blogs}) {
  
  return (
    <div className={styles.container}>
    
    <Head>

      <title>Techoverflow</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      
    </Head>
    
    <main className={styles.main}>
    
      <h1 className={styles.title}>
       <span className="myspan"> BlogSite</span>
      </h1>

      <p className={styles.description}>
      Hello Welcome to New BlogSite
       
      </p>
      <div className={styles.blog}>
        <div className={styles.create}>
        <Link href="/createblog">
        <button>Create Blog</button>
        </Link>
           
        </div>
        <div className={styles.read}>
        <Link href="#showblog">
        <button>Show Blog</button>
        </Link>
        
        </div>
      </div>
     
      <Image className={styles.image} src={homeimg} alt="" width={2000} height={800}
      />
      {/* <img className={styles.image} src="/public/homeimg.jpg" alt="" width={2000} height={800} aly=""
      /> */}
      <section id='showblog'>
      <div className={styles.grid}>
            {blogs && blogs.map((BlogItem)=>{
        
        return <a key={BlogItem._id} href={`/blogpost/${BlogItem._id}`} className={styles.card}>
          <h2>{BlogItem.title} &rarr;</h2>
          
          <p>{BlogItem.content.substr(0,100)}</p>
        </a>
      })}  
      </div>
      </section>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          soumyadip❤️
        </span>
      </a>
    </footer>
  </div>
 
  )
}
export async function getServerSideProps(context) {
  
  if(!mongoose.connections[0].readyState){
    await mongoose.connect("mongodb://localhost:27017/blogspot")
  }
  let blogs = await createblog.find()
  //console.log(blogs)
  return {
    props: {blogs:JSON.parse(JSON.stringify(blogs))}, // will be passed to the page component as props
  }
}